config/routes.rb
Rails.application.routes.draw do
  #tareas
  resources :home_works
  post 'closeWorkHome', to: 'home_works#closeWorkHome'
  
  #apis
  get 'api_app/login'
  get 'api_app/get_users'
  get 'api_app/save_sold'
  get 'api_app/save_registre'
  get 'api_app/get_allR'
  get 'api_app/gps_save'
  get 'api_app/save_bitacora'
  get 'api_app/get_bitacora'
  get 'api_app/getSolicitudsTeam'
  get 'api_app/asistencia'
  get 'api_app/viewNotificacion'
  #update material
  get 'api_app/updateMaterial'
  get 'api_app/removeMaterial'
  get 'api_app/saveMaterial'
  
  #getNotiticaciones

  get'api_app/getNotificacion'
  
  #api de administrador
  get 'api_adm/get_users_proyecto'
  get 'api_adm/getUbicacionesAdm'
  get 'api_adm/getRegistrosAdm'
  get 'api_adm/searchSold'
  get 'api_adm/getSolicitud'
  get 'api_adm/getSolicitudesV'
  get 'api_adm/validateSold'
  get 'api_adm/getStatusSolds'
  get 'api_adm/getSolicitudesF'
  get 'api_adm/finalizarSolicitud'
  
  #scaffolds
  resources :cvehiculos
  resources :registries
  resources :solicituds
  resources :proyectos
  #Roles
  get 'roles',to:"adm#rol", as: "roles"
  get 'crear_rol',to:'adm#new_rol', as: "crear_rol"
  post 'adm/create_rol'
  delete 'delete_rol/:id', to:'adm#delete_rol', as:"delete_rol"
  get 'edit_rol/:id',to:'adm#edit_rol', as: "edit_rol"
  patch 'update_rol',to: 'adm#update_rol'
  #usuarios
  get 'usuarios', to:'adm#user', as: "usuarios"
  get 'nuevoUsuario', to: 'adm#user_new', as: 'nuevoUsuario'
  post 'adm/user_create'
  get 'editar_usuario/:id',to:'adm#user_edit', as: "user_edit"
  patch 'user_update', to: 'adm#user_update'
  delete 'user_delete/:id', to:'adm#user_delete', as:"user_delete"
  get 'edit_password/:id', to: 'adm#editar_password', as: "edit_password"
  patch 'update_password', to: 'adm#update_password'
  # grupos
  get 'equipo', to:'adm#equipo', as: "equipo"
  get 'equipo_nuevo', to: 'adm#equipo_nuevo', as: "equipo_nuevo"
  post 'equipo_create', to: 'adm#equipo_create'
  get 'equipo_edit/:id',to:'adm#equipo_edit', as: "equipo_edit"
  delete 'equipo_delete/:id', to: 'adm#equipo_delete', as: "equipo_delete"
  patch 'equipo_update', to: 'adm#equipo_update'
  
  #Autorizacion cancelacion actualizacion de solicitudes via ajax
  get '/update_materials', to: 'solicituds#update_materials', :defaults => {:format => 'json'}
  get '/update_viaticos', to: 'solicituds#update_viaticos', :defaults => {:format => 'json'}
  get '/validate_materials', to: 'solicituds#validate_materials', :defaults => {:format => 'json'}
  get '/authSolicitud', to: 'solicituds#authSolicitud'
  get '/finSolicitud', to: 'solicituds#finSolicitud'
  get '/cancSolicitud', to: 'solicituds#cancSolicitud'

  #Commonts
  get '/gps', to:'commont#gps'
  get '/asistencias', to:'commont#asistencia'

  authenticated :user do
    root 'dasboard#index'
  end
  unauthenticated :user do
  	devise_scope :user do
  		root 'dasboard#dasboard', as: :unregistered_root
  	end
  end
  devise_for :users
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/proyecto.rb
# == Schema Information
#
# Table name: proyectos
#
#  id          :integer          not null, primary key
#  titulo      :string
#  estado      :string
#  inicio      :date
#  fin         :date
#  descripcion :string
#  user_id     :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Proyecto < ApplicationRecord
  belongs_to :user, optional: true
end

app/controllers/proyectos_controller.rb
class ProyectosController < ApplicationController
  before_action :set_proyecto, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /proyectos
  # GET /proyectos.json
  def index
    @proyectos = Proyecto.all
  end

  # GET /proyectos/1
  # GET /proyectos/1.json
  def show
  end

  # GET /proyectos/new
  def new
    @proyecto = Proyecto.new
  end

  # GET /proyectos/1/edit
  def edit
  end

  # POST /proyectos
  # POST /proyectos.json
  def create
    @proyecto = Proyecto.new(proyecto_params)
    @proyecto.user = current_user
    respond_to do |format|
      if @proyecto.save
        format.html { redirect_to @proyecto, notice: 'Proyecto was successfully created.' }
        format.json { render :show, status: :created, location: @proyecto }
      else
        format.html { render :new }
        format.json { render json: @proyecto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /proyectos/1
  # PATCH/PUT /proyectos/1.json
  def update
    respond_to do |format|
      if @proyecto.update(proyecto_params)
        format.html { redirect_to @proyecto, notice: 'Proyecto was successfully updated.' }
        format.json { render :show, status: :ok, location: @proyecto }
      else
        format.html { render :edit }
        format.json { render json: @proyecto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /proyectos/1
  # DELETE /proyectos/1.json
  def destroy
    @proyecto.destroy
    respond_to do |format|
      format.html { redirect_to proyectos_url, notice: 'Proyecto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_proyecto
      @proyecto = Proyecto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def proyecto_params
      params.require(:proyecto).permit(:titulo, :estado, :inicio, :fin, :descripcion, :user_id)
    end
end

app/helpers/proyectos_helper.rb
module ProyectosHelper
end

app/views/proyectos/_form.html.erb
<div class="card" style="padding: 3%;">
<%= simple_form_for(@proyecto) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
  <div class="row">
    <div class="col-md-2">
      <%= f.label :titulo %>
    </div>
    <div class="col-md-10">
      <%= f.text_field :titulo, class: "form-control" %>
    </div>
  </div>
  <br/>
  <div class="row">
    <div class="col-md-2">
    <%= f.label :estado %>
    </div>
    <div class="col-md-10">
      <%= f.select :estado, [['Abierta',1],['Cerrada',2],['Pausado',3]],{}, class: "form-control" %>  
    </div>
  </div>
  <br/>
  <div class="row">
    <div class="col-md-6">
      <div class="row">
        <div class="col-md-4">
          <%= f.label :inicio%>
        </div>
        <div class="col-md-8">
          <%= f.date_field :inicio,class: "form-control"%>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <div class="row">
        <div class="col-md-4">
          <%= f.label :fin%>
        </div>
        <div class="col-md-8">
          <%= f.date_field :fin,class: "form-control"%>
        </div>
      </div>
    </div>
  </div>
  <br/>
  <div class="row">
    <div class="col-md-2">
      <%= f.label :descripcion %>
    </div>
    <div class="col-md-10">
      <%= f.text_area :descripcion, class: "form-control" %>
    </div>
  </div>
  <br/>
  <div class="form-actions text-center">
    <%= f.submit class: "btn btn-primary" do %>
      Crear Proyecto
    <%end%>
  </div>
  <%= link_to proyectos_path, class: "btn btn-warning" do%>
    <i class="fa fa-arrow-left"></i> Regresar
  <%end%>
<% end %>
</div>

app/views/proyectos/edit.html.erb
<h1>Editar Proyecto</h1>

<%= render 'form', proyecto: @proyecto %>

app/views/proyectos/index.html.erb
<h1>Proyectos</h1>
<div class="float-right">
<%= link_to 'Nuevo Proyecto', new_proyecto_path, class: "btn btn-primary" %>
</div>
<div class="table-responsive">
<table class="responsive nowrap table proyectos" id="dttb-proyectos" data-sort="true" style="font-size: 80%" data-page-length='100'>
  <thead>
    <tr>
      <th>Titulo</th>
      <th>Estado</th>
      <th>Inicio</th>
      <th>Fin</th>
      <th>Descripcion</th>
      <th>User</th>
      <th data-data="url" data-orderable="false" data-class-name="all" data-searchable="false" class="skip-export" width="100px"></th>
    </tr>
  </thead>
  <tbody>
    <% @proyectos.each do |item|%>
      <tr>
        <td><%= item.titulo%></td>
        <td><% if item.estado == "1"%> Abierto <%elsif item.estado == "2"%> Cerrado <%else%> Pausado <%end%>
        </td>
        <td><%= item.inicio%></td>
        <td><%= item.fin%></td>
        <td><%= item.descripcion%></td>
        <td><%= item.user.email%></td>
        <td>
          <%= link_to edit_proyecto_path(item), class: "btn btn-success btn-circle" do%>
            <i class="fas fa-edit"></i>
          <%end%>
            <%= link_to item, method: :delete, class: 'btn btn-danger  btn-circle',data: { confirm:'¿Estas Seguro de eliminar este proyecto?'}  do %>
            <i class="fas fa-trash"></i>
          <%end%>
        </td>
      </tr>
    <%end%>
  </tbody>
</table>
</div>
<br>

app/views/proyectos/new.html.erb
<div class="text-center">
	<h1>Nuevo Proyecto</h1>
</div>

<%= render 'form', proyecto: @proyecto %>

app/views/proyectos/show.html.erb
<p id="notice"><%= notice %></p>
<div class="card" style="padding: 25px;">
<p>
  <strong>Titulo:</strong>
  <%= @proyecto.titulo %>
</p>

<p>
  <strong>Estado:</strong>
  <%= @proyecto.estado %>
</p>

<p>
  <strong>Inicio:</strong>
  <%= @proyecto.inicio %>
</p>

<p>
  <strong>Fin:</strong>
  <%= @proyecto.fin %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @proyecto.descripcion %>
</p>

<p>
  <strong>User:</strong>
  <%= @proyecto.user.email %>
</p>

<%= link_to 'Edit', edit_proyecto_path(@proyecto) %> |
<%= link_to 'Back', proyectos_path %>
</div>