config/routes.rb
Rails.application.routes.draw do
  #tareas
  resources :home_works
  post 'closeWorkHome', to: 'home_works#closeWorkHome'
  
  #apis
  get 'api_app/login'
  get 'api_app/get_users'
  get 'api_app/save_sold'
  get 'api_app/save_registre'
  get 'api_app/get_allR'
  get 'api_app/gps_save'
  get 'api_app/save_bitacora'
  get 'api_app/get_bitacora'
  get 'api_app/getSolicitudsTeam'
  get 'api_app/asistencia'
  get 'api_app/viewNotificacion'
  #update material
  get 'api_app/updateMaterial'
  get 'api_app/removeMaterial'
  get 'api_app/saveMaterial'
  
  #getNotiticaciones

  get'api_app/getNotificacion'
  
  #api de administrador
  get 'api_adm/get_users_proyecto'
  get 'api_adm/getUbicacionesAdm'
  get 'api_adm/getRegistrosAdm'
  get 'api_adm/searchSold'
  get 'api_adm/getSolicitud'
  get 'api_adm/getSolicitudesV'
  get 'api_adm/validateSold'
  get 'api_adm/getStatusSolds'
  get 'api_adm/getSolicitudesF'
  get 'api_adm/finalizarSolicitud'
  
  #scaffolds
  resources :cvehiculos
  resources :registries
  resources :solicituds
  resources :proyectos
  #Roles
  get 'roles',to:"adm#rol", as: "roles"
  get 'crear_rol',to:'adm#new_rol', as: "crear_rol"
  post 'adm/create_rol'
  delete 'delete_rol/:id', to:'adm#delete_rol', as:"delete_rol"
  get 'edit_rol/:id',to:'adm#edit_rol', as: "edit_rol"
  patch 'update_rol',to: 'adm#update_rol'
  #usuarios
  get 'usuarios', to:'adm#user', as: "usuarios"
  get 'nuevoUsuario', to: 'adm#user_new', as: 'nuevoUsuario'
  post 'adm/user_create'
  get 'editar_usuario/:id',to:'adm#user_edit', as: "user_edit"
  patch 'user_update', to: 'adm#user_update'
  delete 'user_delete/:id', to:'adm#user_delete', as:"user_delete"
  get 'edit_password/:id', to: 'adm#editar_password', as: "edit_password"
  patch 'update_password', to: 'adm#update_password'
  # grupos
  get 'equipo', to:'adm#equipo', as: "equipo"
  get 'equipo_nuevo', to: 'adm#equipo_nuevo', as: "equipo_nuevo"
  post 'equipo_create', to: 'adm#equipo_create'
  get 'equipo_edit/:id',to:'adm#equipo_edit', as: "equipo_edit"
  delete 'equipo_delete/:id', to: 'adm#equipo_delete', as: "equipo_delete"
  patch 'equipo_update', to: 'adm#equipo_update'
  
  #Autorizacion cancelacion actualizacion de solicitudes via ajax
  get '/update_materials', to: 'solicituds#update_materials', :defaults => {:format => 'json'}
  get '/update_viaticos', to: 'solicituds#update_viaticos', :defaults => {:format => 'json'}
  get '/validate_materials', to: 'solicituds#validate_materials', :defaults => {:format => 'json'}
  get '/authSolicitud', to: 'solicituds#authSolicitud'
  get '/finSolicitud', to: 'solicituds#finSolicitud'
  get '/cancSolicitud', to: 'solicituds#cancSolicitud'

  #Commonts
  get '/gps', to:'commont#gps'
  get '/asistencias', to:'commont#asistencia'

  authenticated :user do
    root 'dasboard#index'
  end
  unauthenticated :user do
  	devise_scope :user do
  		root 'dasboard#dasboard', as: :unregistered_root
  	end
  end
  devise_for :users
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/adm_controller.rb
class AdmController < ApplicationController
	before_action :set_rol, only: [:edit_rol, :update_rol, :delete_rol]
  before_action :authenticate_user!
  #roles
  def rol
  	@rol = Rol.all()
  end
  
  def new_rol
    Rails.application.eager_load!
  	@rol = Rol.new
  	@rol.permissions.build
    @permisos_all = ApplicationRecord.descendants.collect { |type| type.name }
    @permisos = []
    @permisos_all.each do |item|
      if !["Permission", "EquipoUsuario"].include?(item)
        @permisos.append(item)
      end      
    end
  end
  
  def edit_rol	
  end

  def update_rol
	  respond_to do |format|
      if @rol.update(rol_params)
        format.html { redirect_to roles_path, notice: 'Article was successfully updated.' }
      else
        format.html { render :edit_rol }
      end
    end
	end

  def create_rol
  	@rol = Rol.new(rol_params)
    respond_to do |format|
      if @rol.save
        format.html { redirect_to roles_path, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location:roles_path }
      else
        format.html { render :new_rol }
      end
    end
  end

  def delete_rol
    @rol.destroy
    respond_to do |format|
      format.html { redirect_to roles_path, notice: 'Roles was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
 #Termina roles
 #usuarios
  def user
    @users = User.where(super_user:false).order(activo: :DESC)
  end
  
  def user_new
    @user = User.new
    @rols = Rol.all()
  end
  def user_edit
    @user = User.find(params[:id])
    @rols = Rol.all()
  end

  def user_create
    @user = User.new(user_params)
    respond_to do |format|
       if @user.save
        format.html { redirect_to usuarios_path, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location:usuarios_path }
      else
        format.html { render :user_new }
      end
    end
  end

  def user_update
    @user = User.find(params[:id])
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to usuarios_path, notice: 'Article was successfully updated.' }
      else
        format.html { render :user_edit }
      end
    end
  end

  def user_delete
    @user = User.find(params[:id])
    @user.destroy
    respond_to do |format|
      format.html { redirect_to usuarios_path, notice: 'Usuario a sido borrado' }
      format.json { head :no_content }
    end
  end

  def editar_password
    @user = User.find(params[:id])
  end

  def update_password
    @user = User.find(params[:id])
    respond_to do |format|
      if @user.update(password)
        format.html { redirect_to user_edit_path(@user.id), notice: 'Article was successfully updated.' }
      else
        raise
        format.html { render :user_edit }
      end
    end
  end
#Termina usuarios
#inicia Grupo de Trabajo
  def equipo
    @equipo = Equipo.all()
  end
  def equipo_nuevo
    @equipo = Equipo.new
  end
  def equipo_edit
    @equipo = Equipo.find(params[:id])
  end
  def equipo_create
    @equipo = Equipo.new(grup_params)
    respond_to do |format|
      if @equipo.save
        format.html { redirect_to equipo_path, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location:equipo_path }
      else
        format.html { render :new_rol }
      end
    end
  end
  def equipo_update
    @equipo = Equipo.find(params[:id])
    respond_to do |format|
      if @equipo.update(grup_params)
        format.html { redirect_to equipo_path, notice: 'Article was successfully updated.' }
      else
        format.html { render :user_edit }
      end
    end
  end
  def equipo_delete
    @equipo = Equipo.find(params[:id])
    @equipo.destroy
    respond_to do |format|
      format.html { redirect_to equipo_path, notice: 'Equipo de Trabajo a sido borrado' }
      format.json { head :no_content }
    end
  end
#Termina Grupo de trabajo
  private
  def set_rol
    Rails.application.eager_load!
    @rol = Rol.find(params[:id])
    @permisos_all = ApplicationRecord.descendants.collect { |type| type.name }
    @permisos_existe = Permission.where(rol_id:@rol.id).collect{ |tips| tips.title}
    @permisos = []
    @permisos_all.each do |item|
      if !["Permission", "EquipoUsuario"].include?(item)
        @permisos.append(item)
      end      
    end
  end
  def grup_params
    params.require(:equipo).permit(:nombre,:activo,:user_id, equipo_usuario_attributes: EquipoUsuario.attribute_names.map(&:to_sym).push(:_destroy))
  end
  # Never trust parameters from the scary internet, only allow the white list through.
  def password
    params.require(:user).permit(:password,:password_confirmation,:id)
  end
  def rol_params
    #params.require(:rol).permit(:nombre, :descripcion, :activo, permission_attributes:[:id,:nombre,:activo])
    params.require(:rol).permit(:nombre, :descripcion, :activo, permissions_attributes: Permission.attribute_names.map(&:to_sym).push(:_destroy))
  end

  def user_params
    params.require(:user).permit(:nombre,:token_msj,:apellido,:email,:encrypted_password,:password,:password_confirmation,:rol_id,:users_id,:alias,:activo,:avatar)
  end
end

app/helpers/adm_helper.rb
module AdmHelper
end

app/views/adm/_equipo_usuario.html.erb
<tr>
	<td>
		<%=f.select(:user_id, options_for_select(User.where(activo:true).collect{|titulo| [titulo.nombre,titulo.id]},f.object.user_id),{include_blank: "Seleccionar un usuario"},{class: 'form-control'})%>
	</td>
	<td>
		<%=f.check_box :activo, label: false%>
	</td>
	<td>
		<%= f.input_field :_destroy, as: :hidden%>
		<%= link_to '#', class: "remove_record btn btn-danger  btn-circle" do%>
			<i class="fas fa-trash"></i>
		<%end%>
	</td>
</tr>
						

app/views/adm/_permission.html.erb
<tr>
	<td>
		<%=f.select(:title, options_for_select(@permisos,f.object.title),{include_blank: "Seleccionar pagina"},{class: 'form-control selecciones'})%>
	</td>
	<td>
		<%=f.check_box :active, label: false%>
	</td>
	<td>
		<%= f.input_field :_destroy, as: :hidden%>
		<%= link_to '#', class: "remove_record btn btn-danger  btn-circle" do%>
			<i class="fas fa-trash"></i>

		<%end%>
	</td>
</tr>
						

app/views/adm/edit_rol.html.erb
<div class="row">
  <div class="col-md-2"></div>
  <div class="col-md-8">
    <div class="card" style="padding: 25px;">
      <%= simple_form_for @rol, url:{action:"update_rol"},id: @rol do |f| %>
        <input type="hidden" name="id" value="<%=@rol.id%>">
        <div class="form-group">
          <%= f.text_field :nombre, autofocus: true, class: "form-control form-control-user",placeholder:"Nombre del Rol"%>
        </div>

        <div class="form-group">
          <%= f.text_field :descripcion, autofocus: true, class: "form-control form-control-user",placeholder:"Descripcion del Rol"%>
        </div>
        <div class="form-group">
          <div class="custom-control">
            <%=f.check_box :activo%>
            <%= f.label :activo %>
          </div>
        </div>
        <div class="table-responsive"> 
        <%= link_to_add_row("Agregar Permisos", f,:permissions, class: "btn btn-primary")%>
        <table class="table">
            <thead>
              <tr>
                <th>
                  Pagina
                </th>
                <th>
                  Ver
                </th>
                <th></th>
              </tr>
            </thead>
            <tbody class="fields">
              <%= f.simple_fields_for :permissions do |build|%>
                <%= render 'permission', f: build %>
              <%end%>    
            </tbody>
          </table>
        </div>
        <div class="actions">
          <%= f.submit "Editar Rol", class: "btn btn-primary btn-block"%>
        </div>
      <% end %>
    
    </div>
  </div>
  <div class="col-md-2"></div>
</div>

app/views/adm/editar_password.html.erb
<div class="row">
  <div class="col-md-3">
  </div>
  <div class="col-md-6">
    <div class="card" style="padding: 25px;">
      <%= simple_form_for @user, url:{action:"update_password"}, id: @user do |f| %>
      <input type="hidden" name="id" value='<%=@user.id%>'>
        <div class="field">
          <%= f.label :password, "Nueva Contraseña" %><br />
          <% if @minimum_password_length %>
            <em>(<%= @minimum_password_length %> characters minimum)</em><br />
          <% end %>
          <%= f.password_field :password, autofocus: true, autocomplete: "new-password", class: "form-control" %>
        </div>

        <div class="field">
          <%= f.label :password_confirmation, "Confirmar Contraseña" %><br />
          <%= f.password_field :password_confirmation, autocomplete: "off", class: "form-control" %>
        </div>
        <br/>
        <div class="actions">
          <%= f.submit "Cambiar la contraseña", class: "btn btn-primary btn-block" %>
        </div>
      <%end%>
    </div>
  </div>
  <div class="col-md-3">
  </div>
</div>

app/views/adm/equipo.html.erb
<div class="row">
  <div class="col">
  </div>
  <div class=" col">
    <%=link_to equipo_nuevo_path, class: "btn btn-primary btn-block" do%>
      <i class="fas fa-plus"></i> Agregar Equipo de Trabajo
    <%end%>
  </div>
</div>
<br/>
<div class="table-responsive">
<table class="table table-bordered dataTable"  width="100%" cellspacing="0">
  <thead>
    <tr>
    	<th># Control</th>
      <th>Encargado</th>
      <th>Equipo / Departamento</th>
      <th>Activo</th>
      <th>Editar</th>
    </tr>
  </thead>
  <tbody>
  	<%@equipo.each do |item|%>
  		<tr>
  			<td><%= item.id%></td>
        <td><%= item.user.nombre%></td>
	      <td><%= item.nombre%></td>
	      <td class="text-center "><%if item.activo == true %><i class="fas fa-check-square"><%else%><i class="fas fa-square"><%end%></td>
	      <td class="text-center ">
	      	<%= link_to equipo_edit_path(item), class: "btn btn-success btn-circle" do%>
	      		<i class="fas fa-edit"></i>
	      	<%end%>
          <%= link_to equipo_delete_path(item), method: :delete, class: 'btn btn-danger  btn-circle',data: { confirm:'¿Estas Seguro de eliminar este Equipo de Trabajo?'}  do %>
	      		<i class="fas fa-trash"></i>
	      	<%end%>
	      </td>
    	</tr>
    <%end%>
  </tbody>
</table>
</div>

app/views/adm/equipo_edit.html.erb
<div class="row">
	<div class="col-md-1">
	</div>
	<div class="col-md-10">
		<div class="card" style="padding: 25px;">
			<%= simple_form_for @equipo, url:{action:"equipo_update"} do |f| %>
			<input type="hidden" name="id" value='<%=@equipo.id%>'>
			<div class="row">
				<div class="col-md-6">
					<div class="form-group">
						<%=f.select(:user_id, options_for_select(User.all().collect{|titulo| [titulo.nombre,titulo.id]},@equipo.user_id),{include_blank: "Seleccionar al jefe de equipo"},{class: 'form-control'})%>
					</div>
				</div>
				<div class="col-md-6">
					<div class="form-group">
						<%= f.text_field :nombre, class: "form-control", placeholder: "Nombre del equipo de Trabajo"%>
					</div>
				</div>
			</div>
			<div class="form-group">
				<div class="row">
					<div class="col-md-2">
						<%= f.check_box :activo%>
					</div>
					<div class="col-md-10">
						<%= f.label :activo%>
					</div>
				</div>
			</div>
			<div class="form-group">
           <%= link_to_add_row("Agregar Usuario", f,:equipo_usuario, class: "btn btn-primary")%>
	          <table class="table">
	            <thead>
	              <tr>
	                <th>
	                  Usuario
	                </th>
	                <th>
	                  Activar
	                </th>
	                <th></th>
	              </tr>
	            </thead>
	            <tbody class="fields">
	              <%= f.simple_fields_for :equipo_usuario do |build|%>
	                <%= render 'equipo_usuario', f: build %>
	              <%end%>    
	            </tbody>
	          </table>
	          
	        </div>
			<%=f.submit "Generar Equipo de Trabajo", class: "btn btn-primary btn-block"%>
			<%end%>
		</div>
	</div>
	<div class="col-md-1">
	</div>
</div>

app/views/adm/equipo_nuevo.html.erb
<div class="row">
	<div class="col-md-1">
	</div>
	<div class="col-md-10">
		<div class="card" style="padding: 25px;">
			<%= simple_form_for @equipo, url:{action:"equipo_create"} do |f| %>
			<div class="row">
				<div class="col-md-6">
					<div class="form-group">
						<%=f.select(:user_id, options_for_select(User.where(activo:true).collect{|titulo| [titulo.nombre,titulo.id]}),{include_blank: "Seleccionar al jefe de equipo"},{class: 'form-control'})%>
					</div>
				</div>
				<div class="col-md-6">
					<div class="form-group">
						<%= f.text_field :nombre, class: "form-control", placeholder: "Nombre del equipo de Trabajo"%>
					</div>
				</div>
			</div>
			<div class="form-group">
				<div class="row">
					<div class="col-md-2">
						<%= f.check_box :activo%>
					</div>
					<div class="col-md-10">
						<%= f.label :activo%>
					</div>
				</div>
			</div>
			<div class="form-group">
           <%= link_to_add_row("Agregar Usuario", f,:equipo_usuario, class: "btn btn-primary")%>
	          <table class="table">
	            <thead>
	              <tr>
	                <th>
	                  Usuario
	                </th>
	                <th>
	                  Activar
	                </th>
	                <th></th>
	              </tr>
	            </thead>
	            <tbody class="fields">
	              <%= f.simple_fields_for :equipo_usuario do |build|%>
	                <%= render 'equipo_usuario', f: build %>
	              <%end%>    
	            </tbody>
	          </table>
	          
	        </div>
			<%=f.submit "Generar Equipo de Trabajo", class: "btn btn-primary btn-block"%>
			<%end%>
		</div>
	</div>
	<div class="col-md-1">
	</div>
</div>

app/views/adm/new_rol.html.erb
<div class="row">
  <div class="col-md-2"></div>
  <div class="col-md-8">
    <div class="card" style="padding: 25px;">
      <%= simple_form_for @rol, url:{action:"create_rol"} do |f| %>
        <div class="form-group">
          <%= f.text_field :nombre, autofocus: true, class: "form-control form-control-user",placeholder:"Nombre del Rol"%>
        </div>

        <div class="form-group">
          <%= f.text_field :descripcion, autofocus: true, class: "form-control form-control-user",placeholder:"Descripcion del Rol"%>
        </div>
        <div class="form-group">
          <div class="custom-control custom-checkbox small">
            <%= f.check_box :activo%>

            <%= f.label :activo %>
          </div>
        </div>
        <div class="form-group">
          <%= link_to_add_row("Agregar Permisos", f,:permissions, class: "btn btn-primary")%>
          <table class="table">
            <thead>
              <tr>
                <th>
                  Pagina
                </th>
                <th>
                  Ver
                </th>
                <th></th>
              </tr>
            </thead>
            <tbody class="fields">
              <%= f.simple_fields_for :permissions do |build|%>
                <%= render 'permission', f: build %>
              <%end%>    
            </tbody>
          </table>
          
        </div>

        <div class="actions">
          <%= f.submit "Guardar Rol", class: "btn btn-primary btn-block"%>
        </div>
      <% end %>
    
    </div>
  </div>
  <div class="col-md-2"></div>
</div>

app/views/adm/rol.html.erb
<div class="row">
  <div class="col-lg-10">
  </div>
  <div class=" col-lg-2">
    <%=link_to crear_rol_path, class: "btn btn-primary btn-block" do%>
      <i class="fas fa-plus"></i> Agregar Rol
    <%end%>
  </div>
</div>
<br/>
<div class="table-responsive">
<table class="table table-bordered dataTable"  width="100%" cellspacing="0">
  <thead>
    <tr>
    	<th># Control</th>
      <th>Rol</th>
      <th>Descripcion</th>
      <th>Activo</th>
      <th>Editar</th>
    </tr>
  </thead>
  <tbody>
  	<%@rol.each do |item|%>
  		<tr>
  			<td><%= item.id%></td>
	      <td><%= item.nombre%></td>
	      <td><%= item.descripcion%></td>
	      <td class="text-center "><%if item.activo == true %><i class="fas fa-check-square"><%else%><i class="fas fa-square"><%end%></td>
	      <td class="text-center ">
	      	<%= link_to edit_rol_path(item), class: "btn btn-success btn-circle" do%>
	      		<i class="fas fa-edit"></i>
	      	<%end%>
          <%= link_to delete_rol_path(item), method: :delete, class: 'btn btn-danger  btn-circle',data: { confirm:'¿Estas Seguro de eliminar este rol?'}  do %>
	      		<i class="fas fa-trash"></i>
	      	<%end%>
	      </td>
    	</tr>
    <%end%>
  </tbody>
</table>
</div>

app/views/adm/user.html.erb
<div class="row">
  <div class="col-lg-9 col-md-9 col-sm-9 col-xs-12">
  </div>
  <div class=" col-lg-3 col-md-3 col-sm-3 col-xs-12">
    <%=link_to nuevoUsuario_path, class: "btn btn-primary btn-block" do%>
      <i class="fas fa-plus"></i> Agregar Usuario
    <%end%>
  </div>
</div>
<br/>
<div class="table-responsive">
<table class="table table-bordered dataTable"  width="100%" cellspacing="0">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Correo</th>
      <th>Rol</th>
      <th>Activo</th>
      <th>Editar</th>
    </tr>
  </thead>
  <tbody>
  	<%@users.each do |item|%>
  		<tr>
	      <td><%= item.nombre%> <%= item.apellido%></td>
        <td><%= item.email%></td>
        <td><%if item.rol_id%><%= Rol.where(id:item.rol_id).first().nombre%><%elsif item.super_user%>SuperUsuario<%else%>No cuenta con rol definido<%end%></td>
	      <td class="text-center "><%if item.activo == true %><i class="fas fa-check-square"><%else%><i class="fas fa-square"><%end%></td>
	      <td class="text-center ">
	      	<%= link_to user_edit_path(item), class: "btn btn-success btn-circle" do%>
	      		<i class="fas fa-edit"></i>
	      	<%end%>
          <%= link_to user_delete_path(item), method: :delete, class: 'btn btn-danger  btn-circle',data: { confirm:'¿Estas Seguro de eliminar este Usuario?'}  do %>
	      		<i class="fas fa-trash"></i>
	      	<%end%>
	      </td>
    	</tr>
    <%end%>
  </tbody>
</table>
</div>

app/views/adm/user_edit.html.erb
<h2>Nuevo Usuario</h2>
<%= simple_form_for @user, url:{action:"user_update"}, id: @user do |f| %>
<input type="hidden" name="id" value="<%=@user.id%>">
	<div class="row">
		<div class="col-lg-6 col-md-12">
			<div class="card" style="padding: 15px;">
				<div class="form-group">
					<%=f.text_field :alias, class: "form-control form-control-user", placeholder:"Alias"%>
				</div>
				<div class="form-group">
					<%=f.email_field :email, class: "form-control form-control-user", placeholder:"Correo Electronico"%>
				</div>
				<div class="form-group text-center">
					<%= link_to edit_password_path(@user.id), class: "btn btn-danger" do%>
						Por seguridad Cambiar Contraseña aqui
					<%end%>
    			</div>
    			<div class="form-group">
					<%=f.select(:users_id, options_for_select(User.all().collect{|titulo| [titulo.nombre,titulo.id]},f.object.users_id),{include_blank: "Seleccionar un Superior"},{class: 'form-control'})%>
				</div>
			</div>
		</div>
		<div class="col-lg-6 col-md-12">
			<div class="card" style="padding: 15px;">
				<div class="form-group">
					<div class="row">
						<div class="col-md-4">
							<%if @user.avatar.attached?%>
								<%= image_tag @user.avatar, style: "width:100%;"%>
							<%end%>
						</div>
						<div class="col-md-8">
							<div class="form-group">
								<div class="row">
									<div class="col-md-12">
										<%=f.file_field :avatar, class: "form-control form-control-user", placeholder:"Avatar"%>
										<br/>
									</div>
									<div class="col-md-12">
										<div class="row">
											<div class="col-lg-1 col-sm-1 col-md-1">
												<%=f.check_box :activo%>
											</div>
											<div class="col-lg-9 col-sm-9 col-md-9">
												activo
											</div>
										</div>
									</div>
								</div>
								<br/>
								<div class="form-group">
									<%=f.text_field :nombre, class: "form-control form-control-user", placeholder:"Nombre(s) del Usuario"%>
								</div>
								<div class="form-group">
									<%=f.text_field :apellido, class: "form-control form-control-user", placeholder:"Apellido(s)"%>
								</div>
								<div class="form-group">
									<%=f.text_field :token_msj, class: "form-control form-control-user", placeholder:"Telegram ID"%>
								</div>
							</div>		
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<br/>
	<div class="row">
		<div class="col-md-12">
			<div class="card" style="padding: 15px;">
				<div class="responsive">
					<table class="table">
						<thead>
							<tr>
								<th>
									Elegir Rol
								</th>
								<th></th>
								<th>
								</th>
							</tr>
						</thead>
						<tbody>
							<% @rols.each do |item|%>
							<tr>
								<td><%= item.nombre%></td>
								<td><small><%=item.descripcion%></small></td>
								<td><%= f.radio_button(:rol_id,item.id)%></td>
							</tr>
							<%end%>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
	<br/>
	<div class="row">
		<div class="col-lg-12 col-md-12">
			<div class="card" style="padding: 15px;">
				<%= f.submit "Actualizar Perfil", class: "btn btn-primary" %>
			</div>
		</div>
	</div>
<%end%>

app/views/adm/user_new.html.erb
<h2>Nuevo Usuario</h2>
<%= simple_form_for @user, url:{action:"user_create"} do |f| %>
	<div class="row">
		<div class="col-lg-6 col-md-12">
			<div class="card" style="padding: 15px;">
				<div class="form-group">
					<%=f.text_field :alias, class: "form-control form-control-user", placeholder:"Alias"%>
				</div>
				<div class="form-group">
					<%=f.email_field :email, class: "form-control form-control-user", placeholder:"Correo Electronico"%>
				</div>
				<div class="form-group row">
            <div class="col-sm-6 mb-3 mb-sm-0">
              <%= f.password_field :password, autocomplete: "new-password", class: "form-control form-control-user", placeholder:"Contraseña" %>
            </div>
            <div class="col-sm-6">
              <%= f.password_field :password_confirmation, autocomplete: "new-password", class: "form-control form-control-user",placeholder:"Repite Tu Contraseña" %>
            </div>
          </div>
          		<div class="form-group">
					<%=f.select(:users_id, options_for_select(User.where(super_user:false).collect{|titulo| [titulo.nombre,titulo.id]},f.object.users_id),{include_blank: "Seleccionar un Superior"},{class: 'form-control'})%>
				</div>
			</div>
		</div>
		<div class="col-lg-6 col-md-12">
			<div class="card" style="padding: 15px;">
				<div class="form-group">
					<div class="row">
						<div class="col-md-8">
							<%=f.file_field :avatar, class: "form-control form-control-user", placeholder:"Avatar"%>
						</div>
						<div class="col-md-4">
							<div class="row">
								<div class="col-lg-1 col-sm-1 col-md-1">
									<%=f.check_box :activo%>
								</div>
								<div class="col-lg-9 col-sm-9 col-md-9">
									activo
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="form-group">
					<%=f.text_field :nombre, class: "form-control form-control-user", placeholder:"Nombre(s) del Usuario"%>
				</div>
				<div class="form-group">
					<%=f.text_field :apellido, class: "form-control form-control-user", placeholder:"Apellido(s)"%>
				</div>
				<div class="form-group">
					<%=f.text_field :token_msj, class: "form-control form-control-user", placeholder:"Telegram ID"%>
				</div>
				
			</div>
		</div>
	</div>
	<br/>
	<div class="row">
		<div class="col-md-12">
			<div class="card" style="padding: 15px;">
				<div class="responsive">
					<table class="table">
						<thead>
							<tr>
								<th>
									Elegir Rol
								</th>
								<th></th>
								<th>
								</th>
							</tr>
						</thead>
						<tbody>
							<% @rols.each do |item|%>
							<tr>
								<td><%= item.nombre%></td>
								<td><small><%=item.descripcion%></small></td>
								<td><%= f.radio_button(:rol_id,item.id)%></td>
							</tr>
							<%end%>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
	<br/>
	<div class="row">
		<div class="col-lg-12 col-md-12">
			<div class="card" style="padding: 15px;">
				<%= f.submit "Guardar", class: "btn btn-primary" %>
			</div>
		</div>
	</div>
<%end%>