config/routes.rb
Rails.application.routes.draw do
  #tareas
  resources :home_works
  post 'closeWorkHome', to: 'home_works#closeWorkHome'
  
  #apis
  get 'api_app/login'
  get 'api_app/get_users'
  get 'api_app/save_sold'
  get 'api_app/save_registre'
  get 'api_app/get_allR'
  get 'api_app/gps_save'
  get 'api_app/save_bitacora'
  get 'api_app/get_bitacora'
  get 'api_app/getSolicitudsTeam'
  get 'api_app/asistencia'
  get 'api_app/viewNotificacion'
  #update material
  get 'api_app/updateMaterial'
  get 'api_app/removeMaterial'
  get 'api_app/saveMaterial'
  
  #getNotiticaciones

  get'api_app/getNotificacion'
  
  #api de administrador
  get 'api_adm/get_users_proyecto'
  get 'api_adm/getUbicacionesAdm'
  get 'api_adm/getRegistrosAdm'
  get 'api_adm/searchSold'
  get 'api_adm/getSolicitud'
  get 'api_adm/getSolicitudesV'
  get 'api_adm/validateSold'
  get 'api_adm/getStatusSolds'
  get 'api_adm/getSolicitudesF'
  get 'api_adm/finalizarSolicitud'
  
  #scaffolds
  resources :cvehiculos
  resources :registries
  resources :solicituds
  resources :proyectos
  #Roles
  get 'roles',to:"adm#rol", as: "roles"
  get 'crear_rol',to:'adm#new_rol', as: "crear_rol"
  post 'adm/create_rol'
  delete 'delete_rol/:id', to:'adm#delete_rol', as:"delete_rol"
  get 'edit_rol/:id',to:'adm#edit_rol', as: "edit_rol"
  patch 'update_rol',to: 'adm#update_rol'
  #usuarios
  get 'usuarios', to:'adm#user', as: "usuarios"
  get 'nuevoUsuario', to: 'adm#user_new', as: 'nuevoUsuario'
  post 'adm/user_create'
  get 'editar_usuario/:id',to:'adm#user_edit', as: "user_edit"
  patch 'user_update', to: 'adm#user_update'
  delete 'user_delete/:id', to:'adm#user_delete', as:"user_delete"
  get 'edit_password/:id', to: 'adm#editar_password', as: "edit_password"
  patch 'update_password', to: 'adm#update_password'
  # grupos
  get 'equipo', to:'adm#equipo', as: "equipo"
  get 'equipo_nuevo', to: 'adm#equipo_nuevo', as: "equipo_nuevo"
  post 'equipo_create', to: 'adm#equipo_create'
  get 'equipo_edit/:id',to:'adm#equipo_edit', as: "equipo_edit"
  delete 'equipo_delete/:id', to: 'adm#equipo_delete', as: "equipo_delete"
  patch 'equipo_update', to: 'adm#equipo_update'
  
  #Autorizacion cancelacion actualizacion de solicitudes via ajax
  get '/update_materials', to: 'solicituds#update_materials', :defaults => {:format => 'json'}
  get '/update_viaticos', to: 'solicituds#update_viaticos', :defaults => {:format => 'json'}
  get '/validate_materials', to: 'solicituds#validate_materials', :defaults => {:format => 'json'}
  get '/authSolicitud', to: 'solicituds#authSolicitud'
  get '/finSolicitud', to: 'solicituds#finSolicitud'
  get '/cancSolicitud', to: 'solicituds#cancSolicitud'

  #Commonts
  get '/gps', to:'commont#gps'
  get '/asistencias', to:'commont#asistencia'

  authenticated :user do
    root 'dasboard#index'
  end
  unauthenticated :user do
  	devise_scope :user do
  		root 'dasboard#dasboard', as: :unregistered_root
  	end
  end
  devise_for :users
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/parciales/route/_moda_logout.html.erb
  <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
          <a class="btn btn-primary" href="login.html">Logout</a>
        </div>
      </div>
    </div>
  </div>

app/views/parciales/route/_navs.html.erb
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

          <!-- Sidebar Toggle (Topbar) -->
          <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
            <i class="fa fa-bars"></i>
          </button>


          <!-- Topbar Navbar -->
          <ul class="navbar-nav ml-auto">

            <!-- Nav Item - Search Dropdown (Visible Only XS) -->
            <li class="nav-item dropdown no-arrow d-sm-none">
              <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-search fa-fw"></i>
              </a>
              <!-- Dropdown - Messages -->
              <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in" aria-labelledby="searchDropdown">
                <form class="form-inline mr-auto w-100 navbar-search">
                  <div class="input-group">
                    <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
                    <div class="input-group-append">
                      <button class="btn btn-primary" type="button">
                        <i class="fas fa-search fa-sm"></i>
                      </button>
                    </div>
                  </div>
                </form>
              </div>
            </li>
            <div class="topbar-divider d-none d-sm-block"></div>
              <li class="nav-item">
                <%= link_to destroy_user_session_path, method: :delete ,class: "dropdown-item", data: {confirm:"¿Estas seguro de cerrar sesion?"} do %>  
                  <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                    Logout
                <%end%>
              </li>
            <!-- Nav Item - User Information -->


          </ul>

        </nav>

app/views/parciales/route/_pie.html.erb
<footer class="sticky-footer bg-white">
  <div class="container my-auto">
    <div class="copyright text-center my-auto">
      <span>Copyright &copy; AnsTec 2019</span>
    </div>
  </div>
</footer>

app/views/parciales/route/_sidebar.html.erb
    <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion toggled" id="accordionSidebar">

      <!-- Sidebar - Brand -->
      <%=link_to root_path ,class: "sidebar-brand d-flex align-items-center justify-content-center" do %>
        <div class="sidebar-brand-icon rotate-n-15">
          <i class="fas fa-laugh-wink"></i>
        </div>
        <div class="sidebar-brand-text mx-3">Gestor <sup>5.0</div>
      <%end%>
      
      <hr class="sidebar-divider my-0">
      <li class="nav-item active">
        <%= link_to root_path, class: "nav-link" do%>
          <i class="fas fa-home"></i>
          <span>Inicio</span>
        <%end%>
      </li>
      <% if @permissions_user.include?('GpsSave') or current_user.super_user == true%>
      <li class="nav-item">
        <%= link_to gps_path, class: "nav-link", style: "padding-top:0px; padding-bottom:0px" do%>
          <i class="fas fa-map-marked"></i>
          <span>Ubicaciones</span>
        <%end%>
      </li>
      <%end%>
      <% if @permissions_user.include?('Assistence') or current_user.super_user == true%>
        <li class="nav-item">
          <%= link_to asistencias_path, class: "nav-link", style: "padding-top:0px; padding-bottom:0px" do%>
            <i class="fas fa-list"></i>
            <span>asistencias</span>
          <%end%>
        </li>
      <%end%>
      <% if @permissions_user.include?('User') or @permissions_user.include?('Rol') or @permissions_user.include?('Equipo') or @permissions_user == "super_user"%>
        <li class="nav-item">
          <a class="nav-link collapsed inners" href="#" data-toggle="collapse" data-target="#adm" aria-expanded="true" aria-controls="adm">
            <i class="fas fa-fw fa-cog"></i>
            <span>Administracion</span>
          </a>
          <div id="adm" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
            <div class="bg-white collapse-inner rounded">
              <% if @permissions_user.include?('User') or @permissions_user.include?("super_user")%>
                <%= link_to usuarios_path, class: "collapse-item" do%>
                  <i class="fas fa-user-plus"></i> <span>Usuarios</span>
                <%end%>
              <%end%>
              <% if @permissions_user.include?('Rol') or @permissions_user.include?("super_user")%>
                <%= link_to roles_path, class: "collapse-item" do%>
                  <i class="fas fa-users-cog"></i><span> Roles</span>
                <%end%>
              <%end%>
              <% if @permissions_user.include?('Equipo') or @permissions_user.include?("super_user")%>
                <%= link_to equipo_path, class: "collapse-item" do%>
                  <i class="fas fa-object-group "></i> <span>Equipos de Trabajo</span>
                <%end%>
              <%end%>
              <% if @permissions_user.include?('cvehiculos') or @permissions_user.include?("super_user")%>
                <%= link_to cvehiculos_path, class: "collapse-item" do%>
                  <i class="fas fa-car "></i> <span>Catalogo de Vehiculos</span>
                <%end%>
              <%end%>
            </div>
          </div>
        </li>
      <%end%>
      <%if @permissions_user.include?('Proyecto')or @permissions_user == "super_user"%>
      <li class="nav-item">
        <a class="nav-link collapsed inners" href="#" data-toggle="collapse" data-target="#proyecto" aria-expanded="true" aria-controls="proyecto">
          <i class="fas fa-city "></i>
          <span>Proyectos</span>
        </a>
        <div id="proyecto" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
            <%= link_to proyectos_path, class: "collapse-item" do%>
              <i class="fas fa-object-group "></i> <span>Proyectos</span>
            <%end%>
          </div>
        </div>
      </li>
      <%end%>

      <hr class="sidebar-divider no_margin">
      <div class="sidebar-heading">
        Diario
      </div>
      <li class="nav-item">
        <a class="nav-link collapsed inners" href="#" data-toggle="collapse" data-target="#registro" aria-expanded="true" aria-controls="registro">
          <i class="fas fa-layer-group "></i>
          <span>Bitacora / Tareas</span>
        </a>
        <div id="registro" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
            <% if @permissions_user.include?('HomeWork') or @permissions_user.include?("super_user")%>
            <%= link_to home_works_path, class: "collapse-item" do%>
              <i class="fas fa-folder-plus "></i> <span>Tareas</span>
            <%end%>
            <%end%>
              <%= link_to registries_path, class: "collapse-item" do%>
                <i class="fas fa-folder-plus "></i> <span>Registro Bitacora</span>
              <%end%>
            
            <% if @permissions_user.include?('GpsSave') or @permissions_user.include?("super_user")%>
                <%= link_to cvehiculos_path, class: "collapse-item" do%>
                  <i class="fas fa-car "></i> <span>Catalogo de Vehiculos</span>
                <%end%>
              <%end%>
          </div>
        </div>
      </li>
      <!-- Divider -->
      <hr class="sidebar-divider no_margin">
      <!-- Heading -->
      <div class="sidebar-heading">
        S. de Obra
      </div>

      <!-- Nav Item - Pages Collapse Menu -->
      <li class="nav-item">
        <a class="nav-link collapsed inners" href="#" data-toggle="collapse" data-target="#solicitudes" aria-expanded="true" aria-controls="solicitudes">
          <i class="fas fa-network-wired"></i>
          <span>Solicitudes de Obra</span>
        </a>
        <div id="solicitudes" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
            <%= link_to solicituds_path, class: "collapse-item" do%>
              <i class="fas fa-object-group "></i> <span>Listado de Solicitudes</span>
            <%end%>
          </div>
        </div>
      </li>
      <%if @permissions_user.include?('Objetivo')%>
      <!-- Nav Item - Utilities Collapse Menu -->
      <li class="nav-item">
        <a class="nav-link collapsed inners" href="#" data-toggle="collapse" data-target="#collapseUtilities" aria-expanded="true" aria-controls="collapseUtilities">
          <i class="fas fa-eye"></i>
          <span>Objetivos</span>
        </a>
        <div id="collapseUtilities" class="collapse" aria-labelledby="headingUtilities" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
            <a class="collapse-item" href="utilities-color.html">Registrar Avance</a>
            <a class="collapse-item" href="utilities-border.html">Mis Objetivos</a>
            <a class="collapse-item" href="utilities-animation.html">Historial</a>
          </div>
        </div>
      </li>

      <hr class="sidebar-divider no_margin">
      <%end%>
      <!-- Divider -->
      <hr class="sidebar-divider d-none d-md-block no_margin">

      <!-- Sidebar Toggler (Sidebar) -->
      <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
      </div>

    </ul>