config/routes.rb
Rails.application.routes.draw do
  #tareas
  resources :home_works
  post 'closeWorkHome', to: 'home_works#closeWorkHome'
  
  #apis
  get 'api_app/login'
  get 'api_app/get_users'
  get 'api_app/save_sold'
  get 'api_app/save_registre'
  get 'api_app/get_allR'
  get 'api_app/gps_save'
  get 'api_app/save_bitacora'
  get 'api_app/get_bitacora'
  get 'api_app/getSolicitudsTeam'
  get 'api_app/asistencia'
  get 'api_app/viewNotificacion'
  #update material
  get 'api_app/updateMaterial'
  get 'api_app/removeMaterial'
  get 'api_app/saveMaterial'
  
  #getNotiticaciones

  get'api_app/getNotificacion'
  
  #api de administrador
  get 'api_adm/get_users_proyecto'
  get 'api_adm/getUbicacionesAdm'
  get 'api_adm/getRegistrosAdm'
  get 'api_adm/searchSold'
  get 'api_adm/getSolicitud'
  get 'api_adm/getSolicitudesV'
  get 'api_adm/validateSold'
  get 'api_adm/getStatusSolds'
  get 'api_adm/getSolicitudesF'
  get 'api_adm/finalizarSolicitud'
  
  #scaffolds
  resources :cvehiculos
  resources :registries
  resources :solicituds
  resources :proyectos
  #Roles
  get 'roles',to:"adm#rol", as: "roles"
  get 'crear_rol',to:'adm#new_rol', as: "crear_rol"
  post 'adm/create_rol'
  delete 'delete_rol/:id', to:'adm#delete_rol', as:"delete_rol"
  get 'edit_rol/:id',to:'adm#edit_rol', as: "edit_rol"
  patch 'update_rol',to: 'adm#update_rol'
  #usuarios
  get 'usuarios', to:'adm#user', as: "usuarios"
  get 'nuevoUsuario', to: 'adm#user_new', as: 'nuevoUsuario'
  post 'adm/user_create'
  get 'editar_usuario/:id',to:'adm#user_edit', as: "user_edit"
  patch 'user_update', to: 'adm#user_update'
  delete 'user_delete/:id', to:'adm#user_delete', as:"user_delete"
  get 'edit_password/:id', to: 'adm#editar_password', as: "edit_password"
  patch 'update_password', to: 'adm#update_password'
  # grupos
  get 'equipo', to:'adm#equipo', as: "equipo"
  get 'equipo_nuevo', to: 'adm#equipo_nuevo', as: "equipo_nuevo"
  post 'equipo_create', to: 'adm#equipo_create'
  get 'equipo_edit/:id',to:'adm#equipo_edit', as: "equipo_edit"
  delete 'equipo_delete/:id', to: 'adm#equipo_delete', as: "equipo_delete"
  patch 'equipo_update', to: 'adm#equipo_update'
  
  #Autorizacion cancelacion actualizacion de solicitudes via ajax
  get '/update_materials', to: 'solicituds#update_materials', :defaults => {:format => 'json'}
  get '/update_viaticos', to: 'solicituds#update_viaticos', :defaults => {:format => 'json'}
  get '/validate_materials', to: 'solicituds#validate_materials', :defaults => {:format => 'json'}
  get '/authSolicitud', to: 'solicituds#authSolicitud'
  get '/finSolicitud', to: 'solicituds#finSolicitud'
  get '/cancSolicitud', to: 'solicituds#cancSolicitud'

  #Commonts
  get '/gps', to:'commont#gps'
  get '/asistencias', to:'commont#asistencia'

  authenticated :user do
    root 'dasboard#index'
  end
  unauthenticated :user do
  	devise_scope :user do
  		root 'dasboard#dasboard', as: :unregistered_root
  	end
  end
  devise_for :users
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/registry.rb
# == Schema Information
#
# Table name: registries
#
#  id          :integer          not null, primary key
#  proyecto_id :integer
#  user_id     :integer
#  titulo      :string
#  descripcion :string
#  resultado   :string
#  finalizado  :boolean
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Registry < ApplicationRecord
  belongs_to :proyecto
  belongs_to :user
  validates :titulo, presence: true
  validates :descripcion, presence: true
  validates :resultado, presence: true
  has_one_attached :evidencia
end

app/controllers/registries_controller.rb
class RegistriesController < ApplicationController
  
  before_action :set_registry, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /registries
  # GET /registries.json
  def index
    @permiso = true
    if current_user.super_user or current_user.rol.nombre == "Gerente"
      @registries = Registry.all().order('created_at ASC')
    else  
      rol =  current_user.rol.nombre
      if rol == "JefeDepartamento"
        usuarios = User.where(users_id:current_user.id)
        @registries = Registry.where(user:usuarios.ids).order('created_at ASC')
      elsif @permissions_user.include?("Bitacora")        
        usuarios = User.where(users_id:current_user.id)
        @registries = Registry.where(user:usuarios.ids).order('created_at ASC')
      else
        @permiso = false
        @registries = Registry.where(user:current_user).order('created_at ASC')
      end
    end
  end

  # GET /registries/1
  # GET /registries/1.json
  def show
  end

  # GET /registries/new
  def new
    @registry = Registry.new
  end

  # GET /registries/1/edit
  def edit
  end

  # POST /registries
  # POST /registries.json
  def create
    @registry = Registry.new(registry_params)
    @registry.user = current_user
    @registry.finalizado = true
    respond_to do |format|
      
        if @registry.save
          format.html { redirect_to @registry, notice: 'Registry was successfully created.' }
          format.json { render :show, status: :created, location: @registry }
          format.js {render :show, notice: 'Ingreso Correcto'}
        else
          format.html { render :new, notice: 'Favor de no dejar campos vacios' }
          format.json { render json: @registry.errors, status: :unprocessable_entity }
          format.js {render :json, status: :created, notice: 'Ocurrio un error'}
        end

    end
  end

  # PATCH/PUT /registries/1
  # PATCH/PUT /registries/1.json
  def update
    respond_to do |format|
      if @registry.update(registry_params)
        format.html { redirect_to @registry, notice: 'Registry was successfully updated.' }
        format.json { render :show, status: :ok, location: @registry }
      else
        format.html { render :edit }
        format.json { render json: @registry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /registries/1
  # DELETE /registries/1.json
  def destroy
    @registry.destroy
    respond_to do |format|
      format.html { redirect_to registries_url, notice: 'Registry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_registry
      @registry = Registry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def registry_params
      params.require(:registry).permit(:proyecto_id, :user_id, :titulo, :descripcion, :resultado, :finalizado,:evidencia)
    end
end

app/helpers/registries_helper.rb
module RegistriesHelper
end

app/views/registries/_form.html.erb
<%= simple_form_for(@registry) do |f| %>
  <%= @erros%>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
  <diV class="card" style="padding: 25px;">
  <div class="form-inputs">
    <div class="row">
      <div class="col-md-6">
        <%= f.label :proyecto%>
        <%=f.select :proyecto_id,Proyecto.where(estado:'1').collect{|item| [item.titulo,item.id,{'data-tokens'=>item.titulo}] },{prompt:"Selecciona un Proyecto"},{class: "form-control selectpicker", 'data-live-search': true}%>
      </div>
      <div class="col-md-6">
        <%= f.label :titulo%>
        <%= f.text_field :titulo, class: "form-control",required: true %>
      </div>
    </div>
    <br/>
    <div class="row">
      <div class="col-md-12">
        <%= f.label :descripcion%>
        <%= f.text_area :descripcion, class: "form-control",required: true %>
      </div>
      <div class="col-md-6">
        <div class="row">
          <div class="col-6">
            <%= f.label :evidencia%>
            <%= f.file_field :evidencia, class: "form-control",required: true %>
          </div>
          
          <div class="col-6 text-center">
            <br/>
            <% if f.object.evidencia.attachment != nil%>
              <%if @registry.evidencia.image?%>
                <%=image_tag url_for(@registry.evidencia),width:350%>
              <%else%>
              <%= link_to "Descargar", url_for(@registry.evidencia), class: "btn btn-sm btn-success", target: "_blank" %>
              <%end%>
            <%else%>
              <h5>Sin evidencia</h5>
            <%end%>
          </div>
        </div>
      </div>
      <div class="col-md-6">
        <%= f.label :resultado%>
        <%= f.text_area :resultado, class: "form-control",required: true %>
      </div>
    </div>
    <br/>
  </div>
</diV>
<br/>
  <div class="form-actions w-100 text-center">
    <%= f.button :submit, class: "btn btn-primary" do %>
      Ingresar Registro
    <%end%>
  </div>
<% end %>
<script type="text/javascript">
  $(function () {
    $('select').selectpicker();
  });
</script>

app/views/registries/edit.html.erb
<h1>Editing Registry</h1>

<%= render 'form', registry: @registry %>

<%= link_to @registry , class: "btn btn-info" do%>
    Ver
<%end%>
 |
<%= link_to registries_path , class: "btn btn-warning" do%>
    <i class="fa fa-arrow-left"></i> Regresar
<%end%>

app/views/registries/index.html.erb
<h1>Bitacora de Obra</h1>
<br/>
<div class="float-right">
  <% if @permiso == true%>
    <%= link_to 'Nuevo Registro', new_registry_path, class: "btn btn-primary" %>
  <%end%>
</div>
<div class="table-responsive">
  <table class="responsive nowrap table table-hover" id="dttb-registries" data-sort="true" style="font-size: 75%" data-page-length='100'>
    <thead>
      <tr>
        <th>Proyecto</th>
        <th>User</th>
        <th>Fecha</th>
        <th>Titulo</th>
        <th>Descripcion</th>
        <th>Resultado</th>
        <th>Finalizado</th>
        <th data-data="url" data-orderable="false" data-class-name="all" data-searchable="false" class="skip-export" width="100px"></th>
      </tr>
    </thead>
    <tbody>
      <% @registries.each do |item|%>
        <tr>
          <td><div class="cut-text" style="font-size:80%"><%=item.proyecto.titulo%></div></td>
          <td><%=item.user.nombre%> <%=item.user.apellido%></td>
          <td><sub><%=item.updated_at.to_formatted_s(:long)%></td>
          <td><div><%=item.titulo%></div></sub></td>
          <td><div class="cut-text"><%=item.descripcion%></div></td>
          <td><div class="cut-text"><%=item.resultado%></div></td>
          <td class="text-center"><% if item.finalizado %><i class="fas fa-check"></i><%else%><i class="fas fa-times"></i><%end%></td>
          <td style="padding: 2px">
              <div class="dropdown">
                <button class="btn btn-secondary btn-sm dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Acciones
                </button>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                  <%= link_to 'Visualizar', item , class:"dropdown-item"%>
                  <%= link_to 'Editar', edit_registry_path(item), class:"dropdown-item" %>
                </div>
              </div>
            </td>
        </tr>
      <%end%>
    </tbody>
  </table>
</div>
<br>

app/views/registries/new.html.erb
<h1>New Registry</h1>

<%= render 'form', registry: @registry %>


<br/>
<div class="row">
	<div class="col-md-2">
		<%= link_to registries_path, class: "btn btn-warning" do%>
    		<i class="fa fa-list-ol"></i> Listado
  		<%end%>
	</div>
	<div class="col-md-2">
		<%= link_to root_path, class: "btn btn-info" do %>
      		<i class="fas fa-home"></i> Ir a Inicio
   		<% end %>
	</div>
</div>

app/views/registries/show.html.erb
<div class="w-100 text-center">
<%= link_to registries_path , class: "btn btn-warning" do%>
  <i class="fa fa-list-ol"></i> Listado
<%end%>
 | 
<%= link_to root_path , class: "btn btn-primary" do%>
    <i class="fa fa-home"></i> Ir a Inicio
<%end%>
</div>

<div class="card" style="padding: 25px">
  <div class="row">
    <div class="col-6">
      <p>
        <strong>Proyecto:</strong>
        <%= @registry.proyecto.titulo %>
      </p>

      <p>
        <strong>Titulo:</strong>
        <%= @registry.titulo %>
      </p>

      <p>
        <strong>Descripcion:</strong>
        <%= @registry.descripcion %>
      </p>

      <p>
        <strong>Resultado:</strong>
        <%= @registry.resultado %>
      </p>

      <p>
        <strong>Finalizado:</strong>
        <% if @registry.finalizado %><i class="fas fa-check"></i><%else%><i class="fas fa-times"></i><%end%>
      </p>
    </div>
    <div class="col-6">
      <strong>Evidencia:</strong>
      <% if @registry.evidencia.attachment != nil%>

      <%= link_to "Descargar", url_for(@registry.evidencia), class: "btn btn-sm btn-success", target: "_blank" %>

      
      <%else%>
        <h5>Sin evidencia</h5>
      <%end%>
    </div>
  </div>
  
</div>
<br/>